// Command devsecrets generates a coherent set of DEVELOPMENT secrets and identities for the
// docker-compose stack, so the whole system can process a real authenticated request
// locally. It writes a .env (consumed by deploy/docker-compose.yml) plus a principal
// bearer token and a delegation chain the agent-side CLI can use.
//
//	go run ./cmd/devsecrets --out deploy
//
// Everything it emits is throwaway and clearly labelled DEV ONLY: an ephemeral workload CA,
// a gateway signing seed, a VC issuer + a signed principal credential, and a bootstrap
// token. Never use any of it in production — that is what the KMS/attestation seams are for.
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/getsanad/sanad/delegation"
	"github.com/getsanad/sanad/pkg/types"
	"github.com/getsanad/sanad/vc"
)

const (
	agentID       = "agent-1"
	bootstrapToks = "dev-token=agent-1"
)

func main() {
	out := flag.String("out", "deploy", "directory to write .env and secrets/ into")
	flag.Parse()

	b64 := base64.RawURLEncoding.EncodeToString

	// Workload CA: authority signs credentials with the private half; the gateway trusts the
	// public half.
	caPub, caPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)

	// Gateway passport signing seed (stable across restarts/replicas).
	seed := make([]byte, ed25519.SeedSize)
	_, err = rand.Read(seed)
	must(err)

	// VC issuer + principal identities (did:key).
	issuerPub, issuerPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)
	issuerDID := vc.EncodeDIDKey(issuerPub)
	principalPub, principalPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)
	principalDID := vc.EncodeDIDKey(principalPub)

	// Signed principal credential (the bearer token the agent presents), valid 30 days.
	now := time.Now()
	cred, err := vc.Issue(issuerDID, issuerPriv, vc.Subject{ID: principalDID, Assurance: types.AssuranceOrg}, 30*24*time.Hour, now)
	must(err)
	vcJSON, err := json.Marshal(cred)
	must(err)
	principalToken := b64(vcJSON)

	// Delegation chain principal -> agent-1, scope [read] (optional richer demo).
	chain, err := delegation.NewRoot(principalPriv, principalDID, agentID, delegation.Grant{Tools: []string{"read"}})
	must(err)
	chainJSON, err := json.MarshalIndent(chain, "", "  ")
	must(err)

	adminTok := make([]byte, 16)
	_, err = rand.Read(adminTok)
	must(err)

	// --- write files ---------------------------------------------------------------
	secretsDir := filepath.Join(*out, "secrets")
	must(os.MkdirAll(secretsDir, 0o755))

	env := fmt.Sprintf(`# Generated by "go run ./cmd/devsecrets" — DEV ONLY.
# Do NOT commit this file and do NOT use these values in production.
# Consumed by deploy/docker-compose.yml.
PASSPORT_CA_KEY=%s
PASSPORT_WORKLOAD_CA=%s
PASSPORT_SIGNING_KEY=%s
PASSPORT_VC_TRUSTED_ISSUERS=%s
PASSPORT_BOOTSTRAP_TOKENS=%s
PASSPORT_ADMIN_TOKEN=%s
`, b64(caPriv), b64(caPub), b64(seed), issuerDID, bootstrapToks, hex.EncodeToString(adminTok))

	writeFile(filepath.Join(*out, ".env"), []byte(env), 0o600)
	writeFile(filepath.Join(secretsDir, "principal.token"), []byte(principalToken), 0o600)
	writeFile(filepath.Join(secretsDir, "delegation.json"), chainJSON, 0o600)

	fmt.Printf(`
Wrote dev secrets to %q:
  .env                     -> docker-compose reads this
  secrets/principal.token  -> the principal's VC bearer token
  secrets/delegation.json  -> delegation chain principal -> %s (scope: read)

Identities:
  VC issuer (trusted) : %s
  Principal           : %s
  Agent id            : %s   (bootstrap token: dev-token)

Next:
  cd %s && docker compose up --build
  # then, from the repo root, in another shell:
  go run ./cmd/passport enroll --authority http://localhost:8082 --token dev-token --key agent.key --out cred.json
  PASSPORT_PRINCIPAL_TOKEN=$(cat %s/secrets/principal.token) \
    go run ./cmd/passport proxy --gateway http://localhost:8080 --key agent.key --credential cred.json \
      --delegation %s/secrets/delegation.json &
  curl -s localhost:7070/servers/demo/tools/list | jq .
`, *out, agentID, issuerDID, principalDID, agentID, *out, *out, *out)
}

func writeFile(path string, b []byte, mode os.FileMode) {
	must(os.WriteFile(path, b, mode))
	fmt.Printf("wrote %s\n", path)
}

func must(err error) {
	if err != nil {
		log.Fatalf("devsecrets: %v", err)
	}
}
