// Command devsecrets generates a coherent set of DEVELOPMENT secrets and identities for the
// docker-compose stack, so the whole system can process a real authenticated request
// locally. It writes a .env (consumed by deploy/docker-compose.yml) plus the principal's
// credential, the principal's private key (which the sidecar proves possession of on every
// request), and a delegation chain the agent-side CLI can use.
//
//	go run ./cmd/devsecrets --out deploy
//
// Everything it emits is throwaway and clearly labelled DEV ONLY: an ephemeral workload CA,
// a gateway signing seed, a VC issuer + a signed principal credential, and a bootstrap
// token. Never use any of it in production — that is what the KMS/attestation seams are for.
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/getsanad/sanad/delegation"
	"github.com/getsanad/sanad/pkg/types"
	"github.com/getsanad/sanad/vc"
)

const (
	agentID   = "agent-1"
	devToken  = "dev-token"
	tokenSpec = devToken + "=" + agentID

	// Bootstrap tokens are single-use and short-lived by default (workload.DefaultTokenUses /
	// DefaultTokenTTL), which is right for a deployment and wrong for a laptop: enrolling once
	// and then finding the token spent — after `docker compose up`, a coffee, and a credential
	// that expired in the meantime — is the kind of thing you conclude is broken.
	//
	// So the dev stack asks for a budget out loud, in .env, where it is visible next to the
	// token rather than hidden in a default. 25 enrollments over 24h covers a day of restarting
	// the agent; past either bound, restarting the authority reissues the whole budget
	// (`docker compose restart authority`), because the counters are process-local. That
	// escape hatch is exactly why this attestor is not for production.
	devTokenUses = "25"
	devTokenTTL  = "24h"
)

func main() {
	out := flag.String("out", "deploy", "directory to write .env and secrets/ into")
	flag.Parse()

	b64 := base64.RawURLEncoding.EncodeToString

	// Workload CA: authority signs credentials with the private half; the gateway trusts the
	// public half.
	caPub, caPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)

	// Gateway passport signing seed (stable across restarts/replicas).
	seed := make([]byte, ed25519.SeedSize)
	_, err = rand.Read(seed)
	must(err)

	// VC issuer + principal identities (did:key).
	issuerPub, issuerPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)
	issuerDID := vc.EncodeDIDKey(issuerPub)
	principalPub, principalPriv, err := ed25519.GenerateKey(rand.Reader)
	must(err)
	principalDID := vc.EncodeDIDKey(principalPub)

	// Signed principal credential (the bearer token the agent presents), valid 30 days.
	now := time.Now()
	cred, err := vc.Issue(issuerDID, issuerPriv, vc.Subject{ID: principalDID, Assurance: types.AssuranceOrg}, 30*24*time.Hour, now)
	must(err)
	vcJSON, err := json.Marshal(cred)
	must(err)
	principalToken := b64(vcJSON)

	// Delegation chain principal -> agent-1, scope [read] (optional richer demo).
	chain, err := delegation.NewRoot(principalPriv, principalDID, agentID, delegation.Grant{Tools: []string{"read"}})
	must(err)
	chainJSON, err := json.MarshalIndent(chain, "", "  ")
	must(err)

	adminTok := make([]byte, 16)
	_, err = rand.Read(adminTok)
	must(err)

	// --- write files ---------------------------------------------------------------
	secretsDir := filepath.Join(*out, "secrets")
	must(os.MkdirAll(secretsDir, 0o755))

	env := fmt.Sprintf(`# Generated by "go run ./cmd/devsecrets" — DEV ONLY.
# Do NOT commit this file and do NOT use these values in production.
# Consumed by deploy/docker-compose.yml.
PASSPORT_CA_KEY=%s
PASSPORT_WORKLOAD_CA=%s
PASSPORT_SIGNING_KEY=%s
PASSPORT_VC_TRUSTED_ISSUERS=%s
PASSPORT_BOOTSTRAP_TOKENS=%s
# A bootstrap token defaults to ONE enrollment within 15 minutes. These widen it for the dev
# loop only; a real deployment leaves them unset (and uses attestation, not tokens at all).
# The budget is held in the authority process: `+"`docker compose restart authority`"+` reissues it.
PASSPORT_BOOTSTRAP_USES=%s
PASSPORT_BOOTSTRAP_TTL=%s
PASSPORT_ADMIN_TOKEN=%s
`, b64(caPriv), b64(caPub), b64(seed), issuerDID, tokenSpec, devTokenUses, devTokenTTL, hex.EncodeToString(adminTok))

	writeFile(filepath.Join(*out, ".env"), []byte(env), 0o600)
	writeFile(filepath.Join(secretsDir, "principal.token"), []byte(principalToken), 0o600)
	// The bootstrap token goes in a file rather than into the enroll command line: an argument
	// is readable by every process on the host and is kept in shell history.
	writeFile(filepath.Join(secretsDir, "bootstrap.token"), []byte(devToken), 0o600)
	// The credential alone authenticates nothing: the gateway also requires a per-request
	// proof of possession of the principal's key (vc.HolderProof), which the sidecar builds
	// from this file. Nothing else in the stack ever sees it.
	writeFile(filepath.Join(secretsDir, "principal.key"), []byte(b64(principalPriv)), 0o600)
	writeFile(filepath.Join(secretsDir, "delegation.json"), chainJSON, 0o600)

	fmt.Printf(`
Wrote dev secrets to %q:
  .env                     -> docker-compose reads this
  secrets/principal.token  -> the principal's VC (presented as the bearer token)
  secrets/principal.key    -> the principal's did:key PRIVATE key; the sidecar proves
                              possession of it on every request (holder binding)
  secrets/bootstrap.token  -> the agent's bootstrap token, for "enroll --token-file"
  secrets/delegation.json  -> delegation chain principal -> %s (scope: read)

Identities:
  VC issuer (trusted) : %s
  Principal           : %s
  Agent id            : %s   (bootstrap token in secrets/bootstrap.token)

Next:
  cd %s && docker compose up --build
  # then, from the repo root, in another shell:
  go run ./cmd/passport enroll --authority http://localhost:8082 \
    --token-file %s/secrets/bootstrap.token --key agent.key --out cred.json
  PASSPORT_PRINCIPAL_TOKEN=$(cat %s/secrets/principal.token) \
    go run ./cmd/passport proxy --gateway http://localhost:8080 --key agent.key --credential cred.json \
      --principal-key %s/secrets/principal.key --delegation %s/secrets/delegation.json &
  curl -s localhost:7070/servers/demo/tools/list | jq .

The bootstrap token is good for %s enrollments over %s (DEV settings, in .env; the default is
one enrollment over 15m). When it runs out: "docker compose restart authority" — the budget
lives in that process — or re-run this command for a fresh stack.
`, *out, agentID, issuerDID, principalDID, agentID, *out, *out, *out, *out, *out, devTokenUses, devTokenTTL)
}

func writeFile(path string, b []byte, mode os.FileMode) {
	must(os.WriteFile(path, b, mode))
	fmt.Printf("wrote %s\n", path)
}

func must(err error) {
	if err != nil {
		log.Fatalf("devsecrets: %v", err)
	}
}
